<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>金猪迎春开门红 万元红包大放送</title>
    <link rel="stylesheet" href="http://lebolive-1255651273.file.myqcloud.com/static/activity/css/animate.min.css">
    <link rel="stylesheet" href="http://lebolive-1255651273.file.myqcloud.com/static/activity/css/common.css">
    <script src="http://lebolive-1255651273.file.myqcloud.com/static/activity/js/jquery-1.8.3.min.js"></script>
    <script src="http://lebolive-1255651273.file.myqcloud.com/static/activity/js/media.js"></script>
</head>
<style>
</style>
<body>
<div class="index-content">
    <img class="line animated fadeIn" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/line.png">
    <img class="curtain animated fadeInDown delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/curtain.png">
    <div class="pig-box animated lightSpeedIn">
        <img class="pig animated wobble delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/pig.png">
    </div>
    <img class="scroll animated fadeInUp delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/scroll.png">
    <img class="title animated bounceIn delay-15" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/title.png">
    <img class="cloud-2 animated fadeInUp delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/cloud-2.png">
    <a href="/index/index/anchor/anchor_id/<?php echo $anchor_user_id; ?>"><img class="btn-zbb animated flipInY delay-2" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/btn-zbb.png"></a>
    <a href="/index/index/user/user/<?php echo $user_id; ?>"><img class="btn-yhb animated flipInY delay-2" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/btn-yhb.png"></a>
    <a href="/index/index/reward"><img class="float-jlsm animated fadeInUp delay-2" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/float-jlsm.png"></a>
    <a href="/index/index/rule"><img class="float-hdgz animated fadeInUp delay-25" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/float-hdgz.png"></a>
    <div class="time animated fadeInUp delay-3" style="bottom:7%">
        <b>活动时间</b>
        <span>2019.02.04零点 （大年三十）</span>
        <span>-</span>
        <span>2019.02.18零点 （正月十四）</span>
        <span><br />活动终止或变更最终解释权归本公司所有</span>
    </div>
</div>
</body>
</html>
