<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<title>奖励说明</title>
<link rel="stylesheet" href="http://lebolive-1255651273.file.myqcloud.com/static/activity/css/animate.min.css">
<link rel="stylesheet" href="http://lebolive-1255651273.file.myqcloud.com/static/activity/css/common.css">
<script src="http://lebolive-1255651273.file.myqcloud.com/static/activity/js/jquery-1.8.3.min.js"></script>
<script src="http://lebolive-1255651273.file.myqcloud.com/static/activity/js/media.js"></script>
<style>
</style>
</head>
<body>
<div class="sub-content">
    <img class="line animated fadeIn" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/line.png">
	<img class="curtain animated fadeInDown delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/curtain.png">
    <img class="cloud-2 animated fadeInUp delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/cloud-2.png">
    <img class="title animated bounceIn delay-15" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/title-jlsm.png">
    <div class="info animated fadeIn delay-1">
    	<div class="info-title">累计通话时长排名对应奖励</div>
        <div class="info-sub-title">(仅限主播榜)</div>
        <div style="padding-left:2.5rem">
            第一名：1000元新春现金红包<br>
            第二名：800元新春现金红包<br>
            第三名：500元新春现金红包<br>
            4-10名：100元新春现金红包<br>
        </div>
        <div style="color:#fff">
            当日通话时长超过60分钟，可获得当日收益的5%额外奖励，活动期间内可叠加。
            累计金币消耗排名对应奖励
        </div>
    	<div class="info-title">累计金币消耗排名对应奖励</div>
        <div class="info-sub-title">(仅限用户榜)</div>
        <div style="padding-left:0.5rem">
            第一名：10000雨音币+1年雨音VIP（金币可折现）<br>
            第二名：8000雨音币+9个月雨音VIP（金币可折现）<br>
            第三名：5000雨音币+6个月雨音VIP（金币可折现）<br>
            4-10名：1000雨音币+1个月雨音VIP（金币可折现）<br>
        </div>
    </div>
    <div class="attention">
    	注：本次活动本着公平公正公开规则举办，所有奖励请自行<br>在活动结束后七天内添加平台客服微信领取奖励。
        <div style="color:#ffeaa4; text-align:center;">客服账号：Yuyin-zb</div>
        禁止使用虚假用户账号进行刷单等违备公平竞争的操作，<br>一经发现封停涉事账号取消奖励，排名顺位移动。
    </div>
</div>
</body>
</html>
