<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<title>活动规则</title>
<link rel="stylesheet" href="http://lebolive-1255651273.file.myqcloud.com/static/activity/css/animate.min.css">
<link rel="stylesheet" href="http://lebolive-1255651273.file.myqcloud.com/static/activity/css/common.css">
<script src="http://lebolive-1255651273.file.myqcloud.com/static/activity/js/jquery-1.8.3.min.js"></script>
<script src="http://lebolive-1255651273.file.myqcloud.com/static/activity/js/media.js"></script>
<style>
</style>
</head>
<body>
<div class="sub-content">
    <img class="line animated fadeIn" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/line.png">
	<img class="curtain animated fadeInDown delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/curtain.png">
    <img class="cloud-2 animated fadeInUp delay-1" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/cloud-2.png">
    <img class="title animated bounceIn delay-15" src="http://lebolive-1255651273.file.myqcloud.com/static/activity/images/title-hdgz.png">
    <div class="info animated fadeIn delay-1">
    	针对入驻雨音平台女用户，凡在活动期间内累计通话时长进入前十榜单即可获得对应奖励。（累计通话时长：在活动期间内与其他用户进行视频通话的累计时间）
        <br>
        针对入驻雨音平台女用户，凡在活动期间内当日通话时长达到60分钟，可获得当天（除邀请）所有收益额外5%返佣奖励。（当日累计通话时长：活动期间内每日与其他用户进行视频通话的当天累计时间）
        <br>
        针对普通雨音平台用户，凡在活动期间内累计消耗金币数进入前十榜单即可获得对应奖励。（累计消耗金币：在活动期间内所有消耗的金币累计数量）
    </div>
    <div class="attention">
    	注：本次活动本着公平公正公开规则举办，所有奖励请自行<br>在活动结束后七天内添加平台客服微信领取奖励。
        <div style="color:#ffeaa4; text-align:center;">客服账号：Yuyin-zb</div>
        禁止使用虚假用户账号进行刷单等违备公平竞争的操作，<br>一经发现封停涉事账号取消奖励，排名顺位移动。
    </div>
</div>
</body>
</html>
